name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@f49d301c653f9aa0d99bec7b7f18f2d789e93fa7 # v0.43.4
    with:
      image: ghcr.io/radiorabe/s2i-python
      name: s2i-python
      display-name: RaBe S2I Python Minimal
      tags: minimal rhel8 rabe s2i python python312
      cosign-base-image-only: true
      # base images are multi-platform for developer convenience
      platforms: linux/amd64,linux/arm64
      docker-daemon-config: |
        {
          "features": {
            "containerd-snapshotter": true
          }
        }
  mkdocs:
    permissions:
      contents: write # Required to push the gh-pages branch for documentation deployment.  
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@f49d301c653f9aa0d99bec7b7f18f2d789e93fa7 # v0.43.4
  github-actions:
    permissions:
      contents: read
      security-events: write # so zizmor can publish results to the Security tab
    uses: radiorabe/actions/.github/workflows/test-github-actions.yaml@f49d301c653f9aa0d99bec7b7f18f2d789e93fa7 # v0.43.4
