name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.17.3
    with:
      image: ghcr.io/radiorabe/s2i-python
      name: s2i-python
      display-name: RaBe S2I Python Minimal
      tags: minimal rhel8 rabe s2i python python311
  mkdocs:
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@v0.17.3
