name: Scheduled tasks

on:
  schedule:
    - cron:  '13 12 * * *'
  workflow_dispatch:

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/schedule-trivy.yaml@main
    with:
      image-ref: 'ghcr.io/radiorabe/s2i-python:latest'
